x=input("Enter Your Frist Number: ")
y=input("Enter Your Secoend Number: ")
print("Sum Of Two Number:",int(x)+int(y))
print("\nSubTract Of Two Number:",int(x)-int(y))
print("\nMultipiction Of Two Number:",int(x)*int(y))
print("\nDivition Of Two Number:",int(x)/int(y))